name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Build environments
        run: npm run build:environments
        env:
          API_URL: ${{ secrets.API_URL }}
          AGM_API_KEY: ${{ secrets.AGM_API_KEY }}

      - name: Testing
        run: npm test
